import sqlite3
import re
import pandas as pd

from openai import OpenAI

from src.config import OPENAI_API_KEY

from src.prompts import (
    build_sql_prompt,
    build_business_answer_prompt,
    build_validation_prompt
)

from src.conversation_memory import (
    get_memory_text
)


# ============================================================
# CONFIGURATION
# ============================================================

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATABASE_PATH = os.path.join(BASE_DIR, "credit_risk.db")

client = OpenAI(
    api_key=OPENAI_API_KEY
)

LLM_MODEL = "gpt-4o-mini"


# ============================================================
# DATABASE FUNCTIONS
# ============================================================

def run_query(sql):
    """
    Execute a SQL query and return the result.
    """

    connection = sqlite3.connect(
        DATABASE_PATH
    )

    try:

        result = pd.read_sql_query(
            sql,
            connection
        )

        return result

    finally:

        connection.close()


# ============================================================
# DATABASE SCHEMA
# ============================================================

def get_database_schema():
    """
    Retrieve the schema of the application_train table.
    """

    connection = sqlite3.connect(
        DATABASE_PATH
    )

    try:

        cursor = connection.cursor()

        cursor.execute(
            "PRAGMA table_info(application_train);"
        )

        columns = cursor.fetchall()

        schema = []

        for column in columns:

            column_name = column[1]
            column_type = column[2]

            schema.append(
                f"{column_name} ({column_type})"
            )

        return ", ".join(schema)

    finally:

        connection.close()


# ============================================================
# SQL VALIDATION
# ============================================================

def validate_sql(sql):
    """
    Validate SQL generated by the LLM.

    Only SELECT queries using application_train
    are permitted.
    """

    if not sql:

        return False, "SQL query is empty."


    # --------------------------------------------------------
    # Remove markdown code fences
    # --------------------------------------------------------

    sql = sql.replace(
        "```sql",
        ""
    )

    sql = sql.replace(
        "```",
        ""
    )

    sql = sql.strip()


    # --------------------------------------------------------
    # Must start with SELECT
    # --------------------------------------------------------

    if not re.match(
        r"^\s*SELECT\b",
        sql,
        re.IGNORECASE
    ):

        return False, (
            "Only SELECT queries are allowed."
        )


    # --------------------------------------------------------
    # Forbidden operations
    # --------------------------------------------------------

    forbidden_keywords = [

        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "CREATE",
        "REPLACE",
        "TRUNCATE",
        "ATTACH",
        "DETACH",
        "PRAGMA"

    ]


    for keyword in forbidden_keywords:

        if re.search(
            rf"\b{keyword}\b",
            sql,
            re.IGNORECASE
        ):

            return False, (
                f"Forbidden SQL operation detected: "
                f"{keyword}"
            )


    # --------------------------------------------------------
    # Only application_train table is allowed
    # --------------------------------------------------------

    tables = re.findall(
        r"\b(?:FROM|JOIN)\s+([A-Za-z_][A-Za-z0-9_]*)",
        sql,
        re.IGNORECASE
    )


    for table in tables:

        if table.lower() != "application_train":

            return False, (
                "Only the application_train table "
                "is allowed."
            )


    return True, sql


# ============================================================
# LLM SQL GENERATION WITH CONVERSATION MEMORY
# ============================================================

def generate_sql_with_llm(question):
    """
    Generate SQL using the LLM.

    Previous conversation is included in the prompt so
    contextual questions can be understood.
    """

    # --------------------------------------------------------
    # Get database schema
    # --------------------------------------------------------

    schema = get_database_schema()


    # --------------------------------------------------------
    # Get conversation memory
    # --------------------------------------------------------

    conversation = get_memory_text()


    # --------------------------------------------------------
    # Build prompt
    # --------------------------------------------------------

    prompt = build_sql_prompt(

        question,

        schema,

        conversation

    )


    print()
    print("Conversation context sent to LLM:")
    print(conversation)


    # --------------------------------------------------------
    # Call LLM
    # --------------------------------------------------------

    response = client.chat.completions.create(

        model=LLM_MODEL,

        messages=[

            {
                "role": "system",
                "content": prompt
            }

        ],

        temperature=0

    )


    # --------------------------------------------------------
    # Get SQL
    # --------------------------------------------------------

    sql = response.choices[0].message.content.strip()


    # --------------------------------------------------------
    # Remove markdown if returned
    # --------------------------------------------------------

    sql = sql.replace(
        "```sql",
        ""
    )

    sql = sql.replace(
        "```",
        ""
    )

    sql = sql.strip()


    return sql


# ============================================================
# BUSINESS ANSWER GENERATION
# ============================================================

def generate_business_answer(
    question,
    sql,
    result
):
    """
    Convert SQL results into a readable business answer.
    """

    result_text = result.to_string(
        index=False
    )


    # --------------------------------------------------------
    # Build business answer prompt
    # --------------------------------------------------------

    prompt = build_business_answer_prompt(

        question,

        sql,

        result_text

    )


    # --------------------------------------------------------
    # Call LLM
    # --------------------------------------------------------

    response = client.chat.completions.create(

        model=LLM_MODEL,

        messages=[

            {
                "role": "system",
                "content": prompt
            }

        ],

        temperature=0

    )


    return response.choices[0].message.content.strip()


# ============================================================
# LLM SQL VALIDATION PROMPT
# ============================================================

def validate_sql_with_llm(sql):
    """
    Build the LLM SQL validation prompt.

    The actual safety validation is still performed by
    validate_sql() before SQL execution.
    """

    schema = get_database_schema()

    prompt = build_validation_prompt(
        sql,
        schema
    )

    return prompt


# ============================================================
# RULE-BASED QUERY SYSTEM
# ============================================================

def rule_based_question(question):

    question = question.lower().strip()


    # ========================================================
    # QUERY 1 - DEFAULTED APPLICANTS
    # ========================================================

    if (
        "defaulted applicants" in question
        or "applicants defaulted" in question
        or "number of defaults" in question
        or "defaulted" in question
    ):

        sql = """
        SELECT COUNT(*) AS defaulted_applicants
        FROM application_train
        WHERE TARGET = 1;
        """

        result = run_query(sql)

        total = int(
            result[
                "defaulted_applicants"
            ].iloc[0]
        )

        return (
            f"There are {total:,} "
            f"defaulted applicants."
        )


    # ========================================================
    # QUERY 2 - NON-DEFAULTED APPLICANTS
    # ========================================================

    elif (
        "non-defaulted applicants" in question
        or "non defaulted applicants" in question
        or "did not default" in question
        or "not default" in question
        or "non default" in question
    ):

        sql = """
        SELECT COUNT(*) AS non_defaulted_applicants
        FROM application_train
        WHERE TARGET = 0;
        """

        result = run_query(sql)

        total = int(
            result[
                "non_defaulted_applicants"
            ].iloc[0]
        )

        return (
            f"There are {total:,} "
            f"non-defaulted applicants."
        )


    # ========================================================
    # QUERY 3 - TOTAL APPLICANTS
    # ========================================================

    elif (
        "how many applicants" in question
        or "total applicants" in question
        or "number of applicants" in question
    ):

        sql = """
        SELECT COUNT(*) AS total_applicants
        FROM application_train;
        """

        result = run_query(sql)

        total = int(
            result[
                "total_applicants"
            ].iloc[0]
        )

        return (
            f"There are "
            f"{total:,} "
            f"applicants in the dataset."
        )


    # ========================================================
    # QUERY 4 - AVERAGE INCOME
    # ========================================================

    elif (
        "average income" in question
        or "average applicant income" in question
        or "mean income" in question
    ):

        sql = """
        SELECT AVG(AMT_INCOME_TOTAL) AS average_income
        FROM application_train;
        """

        result = run_query(sql)

        average = float(
            result[
                "average_income"
            ].iloc[0]
        )

        return (
            f"The average applicant "
            f"income is {average:,.2f}."
        )


    # ========================================================
    # QUERY 5 - AVERAGE CREDIT
    # ========================================================

    elif (
        "average credit" in question
        or "average credit amount" in question
        or "mean credit" in question
    ):

        sql = """
        SELECT AVG(AMT_CREDIT) AS average_credit
        FROM application_train;
        """

        result = run_query(sql)

        average = float(
            result[
                "average_credit"
            ].iloc[0]
        )

        return (
            f"The average credit "
            f"amount is {average:,.2f}."
        )


    return None


# ============================================================
# MAIN NL-TO-SQL PIPELINE
# ============================================================

def answer_question(question):
    """
    Main natural-language query pipeline.

    1. Check known safe query patterns.
    2. If no pattern matches, use the LLM.
    3. Include conversation memory in the LLM prompt.
    4. Validate generated SQL.
    5. Execute SQL.
    6. Generate a business-friendly answer.
    """

    if not question:

        return "Please enter a question."


    # ========================================================
    # STEP 1 - SAFE EXISTING PATTERNS
    # ========================================================

    rule_answer = rule_based_question(
        question
    )


    if rule_answer is not None:

        return rule_answer


    # ========================================================
    # STEP 2 - LLM SQL GENERATION
    # ========================================================

    try:

        sql = generate_sql_with_llm(
            question
        )


        print()
        print("Generated SQL:")
        print(sql)


        # ====================================================
        # STEP 3 - SQL VALIDATION
        # ====================================================

        is_valid, validation_result = validate_sql(
            sql
        )


        if not is_valid:

            print(
                "SQL validation failed:",
                validation_result
            )

            return (
                "I could not safely process "
                "that question."
            )


        validated_sql = validation_result


        # ====================================================
        # STEP 4 - UNSUPPORTED QUESTION
        # ====================================================

        if (
            "UNSUPPORTED"
            in validated_sql.upper()
        ):

            return (
                "Sorry, I cannot answer that "
                "question using the available "
                "credit dataset."
            )


        # ====================================================
        # STEP 5 - EXECUTE SQL
        # ====================================================

        result = run_query(
            validated_sql
        )


        # ====================================================
        # STEP 6 - BUSINESS ANSWER
        # ====================================================

        answer = generate_business_answer(

            question,

            validated_sql,

            result

        )


        return answer


    except Exception as e:

        print(
            "LLM processing error:",
            str(e)
        )

        return (
            "I was unable to process that "
            "question using the LLM. "
            "Please try again."
        )


# ============================================================
# TEST
# ============================================================

if __name__ == "__main__":

    test_questions = [

        "How many applicants are there?",

        "How many applicants defaulted?",

        "How many applicants did not default?",

        "What is the average income?",

        "What is the average credit amount?"

    ]


    for question in test_questions:

        print()
        print("=" * 70)

        print("Question:")
        print(question)

        print("-" * 70)

        answer = answer_question(
            question
        )

        print("Answer:")
        print(answer)

        print("=" * 70)